name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.0.0)"
        required: true
        type: string

jobs:    
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract release notes
      id: extract_release_notes
      uses: ffurrer2/extract-release-notes@v1
      with:
        prerelease: true

    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifactErrorsFailBuild: true
        body: ${{ steps.extract_release_notes.outputs.release_notes }}
        tag: v${{ inputs.version }}
        draft: true

    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: ${{ inputs.version }}
